### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by perracolabs** [valentingalea/shaderbox#1]
I tried to play with this project, but, Visual Studio can't compile it because in the file "app.cpp"  the "shader.mainImage" function code is not defined anywhere, only the function signature is specified in the fragment_shader struct but nothing else.

To be more clear, for the next code in app.cpp (line 229), where is the function code definition of shader.mainImage?

// vvvvvvvvvvvvvvvvvvvvvvvvvv
// THE SHADER IS INVOKED HERE
// ^^^^^^^^^^^^^^^^^^^^^^^^^^
shader.mainImage(shader.gl_FragColor, shader.gl_FragCoord);

**Comment by valentingalea** [comment]
Sorry if the project is not better explained.

Basically you select between subprojects with macro defines. See app.cpp lines 94-108. So for example to run the raytracer define APP_RAYTRACER either directly in the file, in the project settings or the makefile.

APP_EGG is an distance field ray marcher animation.
APP_RAYTRACER is a PBR raytracer with simple reflection and refraction.
APP_SDF_AO is a test for ambient occlusion with signed distance fields.
APP_2D is an old-skool demoscene tunnel effect.
APP_TERRAIN is an ongoing test for modeling sky and cloulds (originally I wanted to do some terrain work but gave up)

Enjoy and I will be happy to help with more questions.

**Comment by perracolabs** [comment]
Thank you for your reply and the info, finally I could make it work.

Also I want to add a small note which might be useful to other developers trying this project. Initially it didn't compile with Visual Studio 2015 Community edition, the problem for this other issue was the linker complaining of missing externals on the SDL libs, the solution was as simple as to download the same SDL version sources, to recompile them and to replace the project SDL libs with the recompiled ones.

Thank you
